##################################################
# BESZEL AGENT (Metrics Collector for CachyOS)
##################################################
networks:
  dockerapps-net:
    external: true

services:

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: cachyos-beszel-agent
    hostname: cachyos-beszel-agent
    networks:
      dockerapps-net:
        ipv4_address: 172.20.0.32
        ipv6_address: fd00:dead:beef:2::32
    # No longer need for ports for Push Mode!
    #ports:
      # Expose this port so the VPS Hub can scrape it via Tailscale!
      #- "45876:45876"
    extra_hosts:
      # Intercept Gotify traffic and route it directly over Tailscale!
      - "gotify.${ROOT_DOMAIN}:10.80.0.2"
    environment:
      - TZ=${TZ}   
      - PORT=45876
      # This MUST match the key generated in the VPS Hub UI
      - KEY=${BESZEL_PUBLIC_KEY}
      - TOKEN=${BESZEL_CACHYOS_TOKEN}
      - DOCKER_HOST=tcp://172.20.0.28:2375
      - FILESYSTEM=/dev/nvme0n1p2
      # NEW: Enable Push Mode via WebSockets (Point to Beszel Hub via Tailscale Net)
      - HUB_URL=http://10.80.0.2:8090
    volumes:
      - /home/sfarhan/homelab/cachyos-home/mon-stack/beszel-agent/beszel_agent_data:/var/lib/beszel-agent
      - /:/extra-filesystems/nvme0n1__CachyOS:ro
      - /mnt/crucial500/.beszel:/extra-filesystems/sdc__Scratch_SSD:ro
      - /mnt/vault/.beszel:/extra-filesystems/HDD_Vault:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    restart: unless-stopped