networks:
  dockerapps-net:
    external: true

services:

##################################################
# DOZZLE (Log Viewer)
##################################################
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    hostname: dozzle
    networks:
      dockerapps-net:
        ipv4_address: 172.20.0.26
        ipv6_address: fd00:dead:beef:2::26
    volumes:
      - /home/sfarhan/cachyos-home/mon-stack/dozzle/dozzle-data:/data
    ports:
      # Allows secure access via Tailscale mesh
      - "100.110.20.1:9090:8080"
      - "[fd7a:115c:a1e0::5a39:3504]:9090:8080" # IPv6 Access
      # Allows local access via CachyOS terminal or SSH tunnel
      - "127.0.0.1:9090:8080"
    extra_hosts:
      # Intercept Gotify traffic and route it directly over Tailscale!
      - "gotify.${ROOT_DOMAIN}:100.110.20.2"
    environment:
      # Use the Proxy
      - DOCKER_HOST=tcp://172.20.0.28:2375
    restart: unless-stopped