networks:
  dockerapps-net:
    external: true

services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    hostname: crowdsec
    networks:
      dockerapps-net:
        ipv4_address: 172.20.0.24
        ipv6_address: fd00:dead:beef:2::24
    # Uncomment these since using a central LAPI setup to OVH-VPS
    #ports:
    #  - "127.0.0.1:8088:8080" # Allows host bouncer to reach the API
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISABLE_LOCAL_API=true
      # ADDED: additional collections and scenarios - remove crowdsecurity/caddy since cachyos-caddy no longer running
      - COLLECTIONS=crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/whitelist-good-actors crowdsecurity/linux LePresidente/jellyfin 
      - SCENARIOS=crowdsecurity/http-probing LePresidente/jellyfin-bf crowdsecurity/http-generic-bf
    volumes:
      - /home/sfarhan/homelab/cachyos-home/ops-stack/crowdsec/config:/etc/crowdsec:rw
      - /home/sfarhan/homelab/cachyos-home/ops-stack/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      #- /home/sfarhan/homelab/cachyos-home/gateway-stack/cachyos-caddy/logs:/var/log/caddy:ro
      #Mount Jellyfin's Logs - note to add filename log to acquis.yaml too
      - /home/sfarhan/homelab/cachyos-home/media-stack/jellyfin/jellyfin-config/log:/var/log/jellyfin:ro
      - /home/sfarhan/homelab/cachyos-home/ops-stack/crowdsec/data:/var/lib/crowdsec/data/
      # Added Docker Socket to monitor VoidAuth's instance - not yet configured with Crowdsec
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Read host kernel logs for better detection of host-level attacks (like SSH brute force)
      - /var/log/journal:/var/log/journal:ro
      # Required for journalctl to work properly inside the container 
      - /etc/machine-id:/etc/machine-id:ro   
    restart: unless-stopped
