# ----------------------------------------
# Network Definition - Have already set this up beforehand
# ----------------------------------------
networks:
  dockerapps-net:
    external: true

services:
##################################################
# RADARR (Movie Management)
##################################################
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    networks:
      dockerapps-net:
        ipv4_address: 172.20.0.13  
        ipv6_address: fd00:dead:beef:2::13
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/sfarhan/homelab/cachyos-home/media-stack/arrs/04-radarr/config:/config
      - /mnt/vault/media:/media
      - /mnt/crucial500/downloads:/downloads
    ports:
      # Allows secure access via Tailscale mesh
      - "100.110.20.1:7878:7878"
      - "[fd7a:115c:a1e0::5a39:3504]:7878:7878" # IPv6 Access
      # Allows local access via CachyOS terminal or SSH tunnel
      - "127.0.0.1:7878:7878"
    extra_hosts:
      # Intercept Gotify traffic and route it directly over Tailscale!
      - "gotify.${ROOT_DOMAIN}:100.110.20.2"
    restart: unless-stopped