- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://172.20.0.10:8096
        description: Media Server
        server: cachyos-local
        container: jellyfin
        widget:
          type: jellyfin
          url: http://172.20.0.10:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
          enableBlocks: true

    - Seerr:
        icon: jellyseerr.png
        href: http://172.20.0.12:5055
        description: Request Manager
        server: cachyos-local
        container: seerr
        widget:
          type: jellyseerr
          url: http://172.20.0.12:5055
          key: {{HOMEPAGE_VAR_SEERR_KEY}}
    
    - Radarr:
        icon: radarr.png
        href: http://172.20.0.13:7878
        description: Movie Manager
        server: cachyos-local
        container: radarr
        widget:
          type: radarr
          url: http://172.20.0.13:7878
          key: {{HOMEPAGE_VAR_RADARR_KEY}}

    - Sonarr:
        icon: sonarr.png
        href: http://172.20.0.14:8989
        description: TV Manager
        server: cachyos-local
        container: sonarr
        widget:
          type: sonarr
          url: http://172.20.0.14:8989
          key: {{HOMEPAGE_VAR_SONARR_KEY}}
          
    - Bazarr:
        icon: bazarr.png
        href: http://172.20.0.15:6767
        description: Subtitles
        server: cachyos-local
        container: bazarr
        widget:
          type: bazarr
          url: http://172.20.0.15:6767
          key: {{HOMEPAGE_VAR_BAZARR_KEY}}

    - Prowlarr:
        icon: prowlarr.png
        href: http://172.20.0.20:9696
        description: Indexer Manager
        server: cachyos-local
        container: prowlarr
        widget:
          type: prowlarr
          url: http://172.20.0.20:9696
          key: {{HOMEPAGE_VAR_PROWLARR_KEY}}

    - Profilarr:
        icon: profilarr.png
        href: http://172.20.0.19:6868
        description: Quality & Custom Format Sync
        server: cachyos-local
        container: profilarr
        #widget:
        #  type: profilarr
        #  url: http://172.20.0.19:6868

    - Transmission:
        icon: transmission.png
        href: http://172.20.0.11:9091
        description: VPN Torrent Client
        server: cachyos-local
        container: transmission
        widget:
          type: transmission
          url: http://172.20.0.11:9091
          username: {{HOMEPAGE_VAR_TRANS_USER}}
          password: {{HOMEPAGE_VAR_TRANS_PASS}}

    - QBittorrent:
        icon: qbittorrent.png
        href: http://172.20.0.11:8080
        description: VPN Torrent Client
        server: cachyos-local
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://172.20.0.11:8080
          username: {{HOMEPAGE_VAR_QBIT_USER}}
          password: {{HOMEPAGE_VAR_QBIT_PASS}}

    #- Speedtest:
    #    icon: /icons/speedtest-tracker.png
    #    href: http://192.168.0.100:8085
    #    description: Gluetun VPN Speedtest Tracker
    #    container: speedtest-tracker
    #    widget:
    #      type: speedtest
    #      url: http://192.168.0.100:8085
    #      version: 1
    #      key: {{HOMEPAGE_VAR_SPEEDTEST_KEY}} # required for version 2
    #      bitratePrecision: 3 # optional, default is 0
        
- Management (CachyOS Home Node):

    - Gluetun:
        icon: gluetun.png
        href: "#"
        description: VPN Gateway
        server: cachyos-local
        container: gluetun
        widget:
          type: gluetun
          url: http://172.20.0.11:8000
          key: {{HOMEPAGE_VAR_GLUETUN_KEY}}

    - Netbird Peer - CachyOS:
        icon: /icons/netbird.png
        href: https://netbird.sfhomelab.com/peers
        # added ping to machine's tailscale ID and removed container:
        ping: 10.80.0.1
        description: NetBird Subnet Mesh Network

    - Arcane:
        icon: arcane.png
        href: http://localhost:3552
        description: Container Management
        server: cachyos-local
        container: arcane
        widget:
          type: arcane
          url: http://172.20.0.17:3552
          env: 0 # required, 0 is Arcane default local environment
          key: {{HOMEPAGE_VAR_ARCANE_API_KEY}}
          fields: ["running", "stopped", "total", "image_updates"]
    
    - Dozzle:
        icon: dozzle.png
        href: http://172.20.0.26:8080
        description: Log Viewer
        server: cachyos-local
        container: dozzle
        #widget:
        #  type: dozzle
        #  url: http://172.20.0.26:8080

    - Kopia:
        icon: kopia.png
        href: http://172.20.0.33:51515
        server: cachyos-local
        container: kopia
        widget:
          type: kopia
          url: http://172.20.0.33:51515
          username: {{HOMEPAGE_VAR_KOPIA_USER}}
          password: {{HOMEPAGE_VAR_KOPIA_PASS}}
          snapshotHost: cachyos
          snapshotPath: /data/homelab-services

    #- Authentik:
    #    icon: authentik.png
    #    href: https://auth.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
    #    description: Authentication
    #    container: authentik-server
    #    widget: 
    #      type: authentik
    #      url: http://authentik-server:9000
    #      key: {{HOMEPAGE_VAR_AUTHENTIK_API_TOKEN}}
    #      version: 2

- OVH-VPS Remote Services:

    - Caddy Reverse Proxy:
        icon: caddy.png
        href: https://status.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Edge Router & Web Server
        server: ovh-vps-remote
        container: vps-caddy
        widget:
          type: caddy
          url: http://10.80.0.2:2019/
          fields: ["upstreams", "requests", "requests_failed"]

    - Netbird Peer - OVH-VPS:
        icon: /icons/netbird.png
        href: https://netbird.sfhomelab.com/peers
        # added ping to machine's tailscale ID and removed container:
        ping: 10.80.0.2
        description: NetBird Subnet Mesh Network
    
    - CrowdSec:
        icon: crowdsec.png
        description: Security Brain
        server: ovh-vps-remote
        widget:
          type: crowdsec
          url: http://10.80.0.2:9090
          username: {{HOMEPAGE_VAR_CROWDSEC_USER}}
          password: {{HOMEPAGE_VAR_CROWDSEC_PASS}}
          limit24h: true
          fields: ["bans"]

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://kuma.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Status & Alerting
        server: ovh-vps-remote
        container: uptime-kuma

    - Komodo:
        icon: komodo.png
        href: https://komodo.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Stacks Management
        server: ovh-vps-remote
        container: komodo-core
        widget:
          type: komodo
          url: http://10.80.0.2:9120/
          key: {{HOMEPAGE_VAR_KOMODO_KEY}}
          secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
          showSummary: true # optional, default: false. Takes precedence over showStacks
          showStacks: true # optional, default: false
    
    - VoidAuth:
        icon: /icons/voidauth.png
        href: https://auth2.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        server: ovh-vps-remote
        container: voidauth
        description: Authentication

    - Beszel Hub:
        icon: beszel.png
        href: http://10.80.0.2:8090/
        description: System Monitoring
        server: ovh-vps-remote
        container: beszel-hub
        widget:
          type: beszel
          url: http://10.80.0.2:8090/
          username: {{HOMEPAGE_VAR_BESZEL_USER}}
          password: {{HOMEPAGE_VAR_BESZEL_PASS}}
          systemId: {{HOMEPAGE_VAR_BESZEL_SYSTEMID}}
          version: 2 # optional, default is 1

    - Gotify:
        icon: gotify.png
        href: https://gotify.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Notifications
        server: ovh-vps-remote
        container: gotify
        widget:
          type: gotify
          url: https://gotify.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
          key: {{HOMEPAGE_VAR_GOTIFY_KEY}}

    - GoAccess:
        icon: goaccess.png
        href: http://10.80.0.2:7890/
        description: Web Log Analysis
        server: ovh-vps-remote
        container: goaccess

    - OpenCloud:
        icon: /icons/opencloud.png
        href: https://cloud.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: File Sync & Share
        server: ovh-vps-remote
        container: opencloud
        
    - BentoPDF:
        icon: /icons/bentopdf.png
        href: https://bentopdf.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: PDF Management
        server: ovh-vps-remote
        container: bentopdf