# ----------------------------------------
# Network Definition - Have already set this up beforehand
# ----------------------------------------
networks:
  dockerapps-net:
    external: true

services:
##################################################
# BAZARR (Subtitle/Caption Manager)
##################################################
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    networks:
      dockerapps-net:
        ipv4_address: 172.20.0.15
        ipv6_address: fd00:dead:beef:2::15
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/sfarhan/homelab/cachyos-home/media-stack/arrs/05-bazarr/config:/config
      - /mnt/vault/media:/media
    ports:
      # Allows secure access via Tailscale mesh
      - "100.110.20.1:6767:6767"
      - "[fd7a:115c:a1e0::5a39:3504]:6767:6767" # IPv6 Access
      # Allows local access via CachyOS terminal or SSH tunnel
      - "127.0.0.1:6767:6767"
    restart: unless-stopped