networks:
  dockerapps-net:
    external: true

services:
# ------------------------------------------------
# 1. CADDY (Reverse Proxy)
# ------------------------------------------------
  caddy:
    image: serfriz/caddy-cloudflare-ddns-crowdsec-geoip:latest
    container_name: cachyos-caddy
    hostname: cachyos-caddy
    networks:
      dockerapps-net:
        # Caddy's internal static IP
        ipv4_address: 172.20.0.23
        ipv6_address: fd00:dead:beef:2::23
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - ROOT_DOMAIN=${ROOT_DOMAIN}
      # Caddy comms with Crowdsec
      - CROWDSEC_LAPI_URL=http://crowdsec:8080
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      # This is for Caddy's basic_auth if we were to reverse proxy goaccess to a site via caddy
      #- LOGS_USER=${LOGS_USER}
      #- LOGS_PASS_HASH=${LOGS_PASS_HASH}
    volumes:
      - /home/sfarhan/homelab/cachyos-home/gateway-stack/cachyos-caddy/Caddyfile:/etc/caddy/Caddyfile # Caddy's config file
      - /home/sfarhan/homelab/cachyos-home/gateway-stack/cachyos-caddy/data:/data                      # For certs & persistent data
      - /home/sfarhan/homelab/cachyos-home/gateway-stack/cachyos-caddy/config:/config                  # For Caddy's internal config
      - /home/sfarhan/homelab/cachyos-home/gateway-stack/cachyos-caddy/logs:/var/log/caddy             
      # Mount the Maxmind Folder - Caddy will read from /etc/caddy/maxmind/GeoLite2-Country.mmdb
      - /home/sfarhan/homelab/cachyos-home/gateway-stack/cachyos-maxmind/data:/etc/caddy/maxmind:ro
    restart: unless-stopped
